name: Build Curriculum Vitae

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 2147483647

    - name: Build English CV
      uses: dante-ev/latex-action@latest
      with:
        root_file: curriculum-vitae/curriculum-vitae.tex
        args: -pdflua -interaction=nonstopmode -halt-on-error -shell-escape
    - name: Post-process English CV
      run: |
        mv curriculum-vitae.pdf "Roman Shchekotov English CV.$(date +'%y-%m-%d').pdf"
    - name: Pre-process German CV
      run: |
        sed -i 's/\\documentclass\[\(.*\)\]{doomcv}/\\documentclass\[\1,german\]{doomcv}/g' curriculum-vitae/curriculum-vitae.tex
    - name: Build German CV
      uses: dante-ev/latex-action@latest
      with:
        root_file: curriculum-vitae/curriculum-vitae.tex
        args: -pdflua -interaction=nonstopmode -halt-on-error -shell-escape
    - name: Post-process German CV
      run: |
        mv curriculum-vitae.pdf "Roman Shchekotov German CV.$(date +'%y-%m-%d').pdf"
    - name: Upload artifacts
      uses: actions/upload-artifact@v2
      with:
        name: documents
        path: |
          *.pdf

